//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateXmlWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactnew
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Building { get; set; }
        public string Deputy { get; set; }
        public string OfficePosition { get; set; }
        public string Title { get; set; }
        public string DirectPhoneNo { get; set; }
        public string CallingCenter { get; set; }
        public string Tel { get; set; }
        public string EmailAddress { get; set; }
        public bool Enabled { get; set; }
        public string Pic { get; set; }
        public Nullable<decimal> prsnum { get; set; }
    }
}
