//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateXmlWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingSubjects
    {
        public int Id { get; set; }
        public string SubTitle { get; set; }
        public string Responsible { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public Nullable<int> MeetingId { get; set; }
        public Nullable<int> Creator { get; set; }
    
        public virtual Meetings Meetings { get; set; }
    }
}
