//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateXmlWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meetings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meetings()
        {
            this.MeetingFiles = new HashSet<MeetingFiles>();
            this.MeetingSubjects = new HashSet<MeetingSubjects>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> MeetingNumber { get; set; }
        public string InnerParticipator { get; set; }
        public string OuterParticipator { get; set; }
        public string Location { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingFiles> MeetingFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingSubjects> MeetingSubjects { get; set; }
    }
}
