//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateXmlWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntranetDatabaseString : DbContext
    {
        public IntranetDatabaseString()
            : base("name=IntranetDatabaseString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<View_ContactList> View_ContactList { get; set; }
        public virtual DbSet<contactnew> contactnew { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<TelAdmin> TelAdmin { get; set; }
    }
}
