//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateXmlWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ContactList
    {
        public decimal Prsnum { get; set; }
        public string Nam { get; set; }
        public string NamKhanevadegi { get; set; }
        public string Sharh_Onvan { get; set; }
        public string Proj_Name { get; set; }
        public string Moavenat { get; set; }
        public string NamLatin { get; set; }
        public string Email { get; set; }
        public string NamKhanevadegiLatin { get; set; }
        public string NumBuild { get; set; }
    }
}
